use std::fs;
use std::path::Path;

fn main() {
    // contributors.csv is generated by the CI release pipeline (via stackql-exec)
    // and embedded into the binary at compile time via include_str! in info.rs.
    // For local builds and non-release CI jobs the file may not exist, so create
    // an empty placeholder to keep the build green.
    let csv_path = "contributors.csv";
    if !Path::new(csv_path).exists() {
        fs::write(csv_path, "").expect("Failed to create placeholder contributors.csv");
    }
    println!("cargo:rerun-if-changed=contributors.csv");
}
